wetty:
  image: dnadave/wettyf90:jul2017
  ports:
  - 3000
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: axiohost13
  volumes:
  - /Projects/BIGdata:/data:rw
  stdin_open: true
  net: bridge
  privileged: true
