RTGCore:
  ports:
  - :3000/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: axiohost13
  image: dnadave/rtg-core:jan2016
  volumes:
  - /Projects/BIGdata:/data:rw
  - /home/dnadave/q/Shared/StatGen:/statgen:rw
  stdin_open: true
  net: bridge
  privileged: true
