shinygwas:
  image: dnadave/release_shinydemo:jul2016
  ports:
  - 80
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true
  net: bridge
  privileged: true
  links:
  - shinygwas:shinygwas
shinydata:
  tty: true
  image: dnadave/release_shinydata:jul2016
