.catalog:
  name: "RTGCore and snpEff"
  version: "v0.1-rtg"
  description: "RealTime Genomics Core Tools with snpEff."
  uuid: rtgcore-0
  questions:
    - variable: "AXIO_PORT"
      label: "External Port"
      description: "Port at which you will access terminal on web page."
      type: "int"
      default: 32751
      required: true

RTGCore:
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
