.catalog:
  name: "RStudio with Sequencing Packages"
  version: "v0.4-jun2016"
  description: "RStudio session with Sequencing tagged packages installed"
  uuid: sequencing-0

#sequencing:
#  health_check:
#    port: 8787
#    interval: 2000
#    unhealthy_threshold: 3
#    request_line: GET / HTTP/1.0
#    healthy_threshold: 2
#    response_timeout: 2000
