.catalog:
  name: "WETTY terminal"
  version: "v0.1-jan2016"
  description: "Web based WETTY terminal"
  uuid: wetty-0

wetty:
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
